### ISSUE TITLE
eh br money

### ISSUE THREAD

**Issue by peterkrauz** [RaphaelSilv/shell-currency#1]
https://github.com/RaphaelSilv/shell-currency/blob/35b9e560ba8a4d56e424c1a7bf983e1bc39d391d/currency.sh#L30

**Comment by RaphaelSilv** [comment]
Opa, fixing essa issue. Valeu pelo report.
Vai ficar `echo  "br dinheiros"`

**Comment by peterkrauz** [comment]
🙏 obrigado meu consagrado
